### ISSUE TITLE
RGBAColor estimates color in reverse order when there is no window open

### ISSUE THREAD

**Issue by jamesfer** [macite/swingame#31]
When there is no graphics window open, the RGBAColor function outputs the color into ARGB format, however when there is a graphics window open, it produces the color in BGRA format.
[Function is here.](https://github.com/macite/swingame/blob/a92631e608aad14d14d9e12c6b87065abdb57961/CoreSDK/src/sgGraphics.pas#L3406)
Eg.
```pascal
RedBefore := RGBAColor(255, 0, 0, 255);
BlueBefore := RGBAColor(0, 0, 255, 255);
PurpleBefore := RGBAColor(255, 0, 255, 255);
OliveBefore := RGBAColor(163, 193, 85, 255);

OpenGraphicsWindow('Test', 800, 500);

RedAfter := RGBAColor(255, 0, 0, 255);
BlueAfter := RGBAColor(0, 0, 255, 255);
PurpleAfter := RGBAColor(255, 0, 255, 255);
OliveAfter := RGBAColor(163, 193, 85, 255);

Writeln(Format('%X', [RedBefore]),    ' : ', Format('%X', [RedAfter]));
Writeln(Format('%X', [BlueBefore]),   ' : ', Format('%X', [BlueAfter]));
Writeln(Format('%X', [PurpleBefore]), ' : ', Format('%X', [PurpleAfter]));
Writeln(Format('%X', [OliveBefore]),  ' : ', Format('%X', [OliveAfter]));
```
Would output
```
FFFF0000 : FFFF
FF0000FF : FF0000FF
FFFF00FF : FF00FFFF
FFA3C155 : 55C1A3FF
```

Note: there are also two spelling errors on lines [279](https://github.com/macite/swingame/blob/a92631e608aad14d14d9e12c6b87065abdb57961/CoreSDK/src/sgGraphics.pas#L279) and [289](https://github.com/macite/swingame/blob/a92631e608aad14d14d9e12c6b87065abdb57961/CoreSDK/src/sgGraphics.pas#L289) where it says RBG instead of RGB, which is what I assumed you meant.

**Comment by macite** [comment]
With the current version the format of the color isn't known until the window is opened. So in some cases this is wrong, but not in all cases :(. This issue should be resolved in the next version where we use our own color format rather than using the display format.
