### ISSUE TITLE
Unable to build source in Linux

### ISSUE THREAD

**Issue by revamped83** [macite/swingame#33]
##    Packaging SwinGame Templates

---
##    Generating the code for SGSDK.pas
-  Running python script: create_sgsdk_code.py
-  Copying code to dist source directory
-  Setting version to 3.03

---
##    Compiling SGSDK framework/dll
-  Running bash script: ['/home/tom/Downloads/swingame-4_backend/Dist/Source/build.sh']
  Error running script:  /home/tom/Downloads/swingame-4_backend/Dist/Source/build.sh   None
  --------------------------------------------------
        Creating SwinGame Dynamic Library
               for Linux
  --------------------------------------------------
  Running script from /home/tom/Downloads/swingame-4_backend/Dist/Source
  Saving output to ./bin/linux
  Compiling with -O3 -fPIC -Sewn -vwn -dSWINGAME_LIB
  --------------------------------------------------
  ... Using SDL 1.2 Driver
  ... Compiling Library
  Error compiling SGSDK
  Free Pascal Compiler version 3.0.0 [2015/11/20] for x86_64
  Copyright (c) 1993-2015 by Florian Klaempfl and others
  Target OS: Linux for x86-64
  Compiling ./src/SGSDK.pas
  Compiling ./src/sgTrace.pas
  Compiling ./src/stringhash.pas
  Compiling ./src/hashtable.pas
  Compiling ./src/comparable.pas
  Compiling ./src/sgResources.pas
  Compiling ./src/sgTypes.pas
  Compiling ./src/sgShared.pas
  Compiling ./src/sgInputBackend.pas
  Compiling ./src/sgDriverInput.pas
  Compiling ./src/sgDriverInputSDL.pas
  Compiling ./src/sdl.pas
  Compiling ./src/sdl_ttf.pas
  Compiling ./src/sgDriverInput.pas
  Compiling ./src/sgInput.pas
  Compiling ./src/sgPhysics.pas
  Compiling ./src/sgGraphics.pas
  Compiling ./src/sgSavePNG.pas
  Compiling ./src/sgShared.pas
  Compiling ./src/sgImages.pas
  Compiling ./src/sgResources.pas
  Compiling ./src/sgSharedUtils.pas
  Compiling ./src/sgText.pas
  Compiling ./src/sgUtils.pas
  Compiling ./src/sgGeometry.pas
  Compiling ./src/sgCamera.pas
  Compiling ./src/sgSprites.pas
  Compiling ./src/sgNamedIndexCollection.pas
  sgNamedIndexCollection.pas(120,120) Warning: Function result variable does not seem to initialized
  sgNamedIndexCollection.pas(115,3) Warning: Function result variable does not seem to initialized
  sgNamedIndexCollection.pas(222) Fatal: There were 2 errors compiling module, stopping
  Fatal: Compilation aborted
  Error: /usr/bin/ppcx64 returned an error exitcode
  `

**Comment by macite** [comment]
Fixed in 4.

**Comment by ghost** [comment]
What was the fix? I'm having this problem trying to install the Swingame 3 from both the Swingame and Swinburne Canvas (3.6, 3.6.1 I think). This is a fresh debian install to write a good "Getting started on Linux" tutorial for the new Swinburne Canvas, so I'm not sure moving to 4 is an option. Although I guess a case could be made :)

**Comment by macite** [comment]
You could have a look at the code in the files that have the issue.

This is no longer an active project. You should have a look at [SplashKit](https://www.splashkit.io) - which is the evolution of this project.

**Comment by macite** [comment]
These are also warnings that are errors because of the compiler option `-Sewn`. Removing that setting will allow it to compile.

**Comment by ghost** [comment]
Great, thanks for the quick response. I'll turn warnings off for the moment, and check out SplashKit for the future. Thanks!
