### ISSUE TITLE
VectorNormal (Pascal) crashes when passed a zero vector

### ISSUE THREAD

**Issue by michaelb958** [macite/swingame#39]
Here, try it:

```
program VectorNormalCrashTest;
uses SwinGame, sgTypes;
begin
  VectorNormal(VectorTo(0, 0));
end.
```

```
EInvalidOp: Invalid floating point operation
```

The cause is fairly obvious: [`VectorNormal` is dividing by the magnitude](https://github.com/macite/swingame/blob/f15efcc096a3d641565e61bd4727be99673b3e8a/CoreSDK/src/sgGeometry.pas#L1989) (the variable isn't helpfully named, either). This would be less of a hassle if I was calling `VectorNormal` directly. Unfortunately, I'm not - it's happening from `CollideCircleLine`, and refactoring my code to avoid that would be a lot of trouble.

**Comment by jgardner8** [comment]
You've already done the hard part of diagnosing it, you might as well submit a pull request and get credit for the fix. :)
